name: Deploy Telegram Bot

# Define los eventos que activarán el workflow
on:
  push:       # Se ejecuta cuando hay un push a cualquier rama
    branches:
      - main  # Asegúrate de que el nombre de tu rama sea 'main'
  workflow_dispatch: # Permite iniciar el workflow manualmente

# Definición de trabajos
jobs:
  deploy:
    runs-on: ubuntu-latest  # Elige el sistema operativo para ejecutar el job

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Versión de Python compatible con tu script

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Paso 4: Ejecutar el bot
      - name: Run Telegram bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # Referencia al secreto
        run: |
          python main.py  # Asegúrate de que tu script se llame 'main.py'
