name: Run BTC Bot

on:
  push:
    branches:
      - main   # Se ejecuta cada vez que haya un 'push' a la rama main
  schedule:
    - cron: '0 * * * *'  # Ejecutar cada hora (puedes modificar el cron según tus necesidades)
  workflow_dispatch:  # Permite disparar manualmente el flujo desde la interfaz de GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # O la versión que estés utilizando

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run BTC Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}  # Asegúrate de configurar el token en los secretos de GitHub
        run: |
          python btc_bot.py
